'use strict';

// The Lucide icons this product uses, and only those — TASK-050.
//
//   node tools/icons/build.js /path/to/lucide-static/icon-nodes.json
//
// Lucide (https://lucide.dev, ISC) is not a dependency and is not installed by
// `npm install`: `05_TECH_SPEC.md` §2 keeps this product at four runtime dependencies,
// no build step, and — through the renderer's CSP — no remote asset. So the icons are
// **vendored**: `npm pack lucide-static@1.45.0` anywhere, point this at the
// `icon-nodes.json` inside, and it writes two files from the names the renderer asks for.
//
//   public/js/shell/icons.js   every name used from JavaScript — `icon: 'printer'` on an
//                              `h()` call, `iconEnd: …`, or `icon('…')` / `iconSvg('…')`
//   public/css/icons.css       every name used from CSS — `var(--icon-…)`, as a data: URI
//                              the stylesheets use as a mask, so a status class such as
//                              `.close-verdict.beyond` carries its icon wherever it is used
//
// Scanning rather than listing, so an icon is added by using it and removed by no longer
// using it, and the vendored set is never larger than the product. `renderer.test.js`
// fails if the renderer names an icon these files do not have — run this again then.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const PUBLIC = path.join(ROOT, 'public');
const VERSION = '1.45.0';

const LICENSE = `Lucide icons v${VERSION} — https://lucide.dev
ISC License. Copyright (c) 2026 Lucide Icons and Contributors.
Permission to use, copy, modify, and/or distribute this software for any purpose with or
without fee is hereby granted, provided that the above copyright notice and this
permission notice appear in all copies. THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL,
DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS
ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
Portions of this software are derived from Feather (MIT), Copyright (c) 2013-2023 Cole Bemis.`;

function filesUnder(dir, ext) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return filesUnder(full, ext);
    return entry.name.endsWith(ext) ? [full] : [];
  });
}

const GENERATED_JS = path.join(PUBLIC, 'js', 'shell', 'icons.js');
const GENERATED_CSS = path.join(PUBLIC, 'css', 'icons.css');

/** The names the renderer uses, from JavaScript and from CSS. Exported for the test. */
function namesUsed() {
  const js = new Set();
  for (const file of filesUnder(path.join(PUBLIC, 'js'), '.js')) {
    if (file === GENERATED_JS) continue;
    const source = fs.readFileSync(file, 'utf8');
    for (const m of source.matchAll(/\b(?:icon|iconEnd)\s*:\s*'([a-z0-9-]+)'/g)) js.add(m[1]);
    for (const m of source.matchAll(/\b(?:icon|iconSvg)\(\s*'([a-z0-9-]+)'/g)) js.add(m[1]);
    // A table of names — `{ …, icon: 'receipt' }` is caught above; this is for the one
    // place a name is computed from data, which declares its candidates in a comment.
    for (const m of source.matchAll(/@icons\s+([a-z0-9 -]+)/g)) m[1].trim().split(/\s+/).forEach((n) => js.add(n));
  }
  const css = new Set();
  for (const file of filesUnder(path.join(PUBLIC, 'css'), '.css')) {
    if (file === GENERATED_CSS) continue;
    for (const m of fs.readFileSync(file, 'utf8').matchAll(/var\(--icon-([a-z0-9-]+)\)/g)) css.add(m[1]);
  }
  return { js: [...js].sort(), css: [...css].sort() };
}

const attrs = (a) => Object.entries(a).map(([k, v]) => `${k}="${v}"`).join(' ');
const inner = (node) => node.map(([tag, a]) => `<${tag} ${attrs(a)}/>`).join('');

function build(iconNodes) {
  const { js, css } = namesUsed();
  const missing = [...js, ...css].filter((name) => !iconNodes[name]);
  if (missing.length) throw new Error(`Not in Lucide ${VERSION}: ${[...new Set(missing)].join(', ')}`);

  const jsOut = `// GENERATED by tools/icons/build.js — do not edit; use an icon and run the tool again.
//
${LICENSE.split('\n').map((l) => `// ${l}`).join('\n')}

// Every icon the renderer uses, as the inside of a 24×24 Lucide SVG. Drawn in
// currentColor, so an icon is always the colour of the words beside it.

export const ICONS = Object.freeze({
${js.map((name) => `  '${name}': '${inner(iconNodes[name])}',`).join('\n')}
});

// No xmlns: the markup is only ever parsed by innerHTML, whose HTML parser puts <svg>
// in the SVG namespace by itself.
const OPEN = (name) => \`<svg class="icon icon-\${name}" viewBox="0 0 24 24" fill="none" \`
  + 'stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" '
  + 'aria-hidden="true" focusable="false">';

/** The icon as markup, for the few places that build HTML as a string. */
export function iconSvg(name) {
  if (!ICONS[name]) throw new Error(\`No icon "\${name}" — run tools/icons/build.js\`);
  return \`\${OPEN(name)}\${ICONS[name]}</svg>\`;
}

/**
 * The icon as an element. Decorative (\`aria-hidden\`): an icon here always sits beside
 * the word it illustrates, or on a control that carries an \`aria-label\` — it is never
 * the only way something is said (04_UX_SPEC.md §8).
 */
export function icon(name) {
  const holder = document.createElement('span');
  holder.innerHTML = iconSvg(name);
  return holder.firstChild;
}
`;

  const cssOut = `/* GENERATED by tools/icons/build.js — do not edit; use an icon and run the tool again.

${LICENSE}

   The icons the stylesheets draw, as data: URIs for \`mask-image\` — the CSP allows data:
   images and nothing remote. A mask takes its colour from \`background-color\`, so an icon
   drawn this way is the colour of the rule that draws it. */

:root {
${css.map((name) => {
    const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='black' `
      + `stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>${inner(iconNodes[name]).replace(/"/g, "'")}</svg>`;
    return `  --icon-${name}: url("data:image/svg+xml,${encodeURIComponent(svg).replace(/%20/g, ' ').replace(/%3D/g, '=').replace(/%3A/g, ':').replace(/%2F/g, '/').replace(/%27/g, "'").replace(/%2C/g, ',')}");`;
  }).join('\n')}
}
`;

  return { js: jsOut, css: cssOut, names: { js, css } };
}

module.exports = { namesUsed, build, GENERATED_JS, GENERATED_CSS };

if (require.main === module) {
  const source = process.argv[2];
  if (!source) {
    process.stderr.write('usage: node tools/icons/build.js /path/to/lucide-static/icon-nodes.json\n');
    process.exit(2);
  }
  const out = build(JSON.parse(fs.readFileSync(source, 'utf8')));
  fs.writeFileSync(GENERATED_JS, out.js);
  fs.writeFileSync(GENERATED_CSS, out.css);
  process.stdout.write(`${out.names.js.length} icons to ${path.relative(ROOT, GENERATED_JS)}, `
    + `${out.names.css.length} to ${path.relative(ROOT, GENERATED_CSS)}\n`);
}
